In [ ]:
import numpy as np

#load in numpy


In [ ]:
a = np.array([1,2,3])
print(a)
#get dimension
print(a.ndim)
#get shape
print(a.shape)
#get type
print(a.dtype)
#get size
print(a.itemsize)
#get totelsize
a.nbytes

[1 2 3]
1
(3,)
int64
8


24

In [ ]:
b = np.array([[1.0,3.2,4.3],[3.6,7.3,8.2]],dtype='int16')
print(b)
#get dimension
print(b.ndim)
#get shape
print(b.shape)
#get type
print(b.dtype)
#get size
print(b.itemsize)
#get total size
b.nbytes

[[1 3 4]
 [3 7 8]]
2
(2, 3)
int16
2


12

# Accessing /changing specific element roe,column etc


In [ ]:
a = np.array([[11,4,6,8,0,4,6],[2,5,7,45,6,2,7]])
a.shape


(2, 7)

In [ ]:
#get specific element[r,c]
a[1,3]


np.int64(45)

In [ ]:
#get specific row
a[0, :]

array([11,  4,  6,  8,  0,  4,  6])

In [ ]:
#get specific column
a[: , 1]

array([4, 5])

In [ ]:
#getting fancy [startindex:end:step]
a[1, 1:6:2]

array([ 5, 45,  2])

In [ ]:
print(a)

[[11  4  6  8  0  4  6]
 [ 2  5  7 45  6  2  7]]


In [ ]:
a[0,4]=9
a

array([[11,  4,  6,  8,  9,  4,  6],
       [ 2,  5,  7, 45,  6,  2,  7]])

In [ ]:
a[: , 2]=[5, 5]
a


array([[11,  4,  5,  8,  9,  4,  6],
       [ 2,  5,  5, 45,  6,  2,  7]])

# 3d example


In [ ]:
a=np.array([[[2,3],[4,5]],[[7,6],[8,9]]])
a

array([[[2, 3],
        [4, 5]],

       [[7, 6],
        [8, 9]]])

In [ ]:
#get a specific element(work outside in)
a[0,1,0]

np.int64(4)

In [ ]:
a[:,1,:]

array([[4, 5],
       [8, 9]])

In [ ]:
#replace
a[:,0,:]=[[4,8],[6,1]]
a

array([[[4, 8],
        [4, 5]],

       [[6, 1],
        [8, 9]]])

# initilize different type of array

In [ ]:
#all 0 matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#all 1 matrx
np.ones((4,3),dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
#any other numbers
np.full((2,3),99,dtype='float32')

array([[99., 99., 99.],
       [99., 99., 99.]], dtype=float32)

In [ ]:
#anu other number(full_like,full)
np.full_like(a,4)



array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [ ]:
#same
np.full(a.shape,4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [ ]:
#random decimal number
np.random.rand(4,2)

array([[0.77151134, 0.04189177],
       [0.78643629, 0.27015294],
       [0.85671312, 0.94294275],
       [0.48884686, 0.14606299]])

In [ ]:
#same
np.random.random_sample(a.shape)

array([[[0.79092045, 0.87711382],
        [0.72893156, 0.38469152]],

       [[0.62118406, 0.70699431],
        [0.47808326, 0.08229054]]])

In [ ]:
#randome integer value
np.random.randint(-4,7,size=(3,3))

array([[-3,  0,  2],
       [ 4,  5,  6],
       [ 5,  3,  1]])

In [ ]:
#indentity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
n=np.array([[1,2,3]])
c=np.repeat(n,3,axis=0)
print(c)  #repeat an array

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
output=np.ones((5,5),dtype='int32')
output

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [ ]:
#copy array
a=np.array([1,2,3])
b=a.copy()
b[0]=100

print(b)
print(a)

[100   2   3]
[1 2 3]


# mathematic

In [ ]:
a =np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
a+2


array([3, 4, 5, 6])

In [ ]:
a*2

array([2, 4, 6, 8])

In [ ]:
a/3

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [ ]:
b=np.array([9,8,7,6])
b+a

array([10, 10, 10, 10])

In [ ]:
b**2

array([81, 64, 49, 36])

In [ ]:
#take the sign of all value
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

#liner algebra

In [ ]:
a = np.full((2,3),2)
print(a)

b = np.ones((3,4))
print(b)

np.matmul(a,b)

[[2 2 2]
 [2 2 2]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


array([[6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
c = np.identity(3)
np.linalg.det(c)


np.float64(1.0)

# Statistics **bold text**

In [ ]:
stats = np.array([[1,2,4],[4,3,2]])
stats

array([[1, 2, 4],
       [4, 3, 2]])

In [ ]:
np.min(stats, axis=0)

array([1, 2, 2])

In [ ]:
np.max(stats)

np.int64(4)

In [ ]:
np.sum(stats)

np.int64(16)

# Reorganize array

In [ ]:
before=